server:
  port: 8082

spring:
  application:
    name: lms-telemetry-service
  data:
    mongodb:
      uri: ${DB_MONGO_URI:mongodb+srv://sanjaysharmajr07_db_user:2qhwUbhjsWNykJK4@enterprisecluster.gtynvaw.mongodb.net/enterprise_db?appName=enterpriseCluster}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: telemetry-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: WARN
    com.edtech.lms: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always
