server.port=8083
spring.application.name=lms-course-service

# Database configuration
spring.datasource.url=${DB_MYSQL_URL:jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/enterprise_db?zeroDateTimeBehavior=convertToNull}
spring.datasource.username=${DB_MYSQL_USERNAME:3tMT9yHQkqHVYMk.root}
spring.datasource.password=${DB_MYSQL_PASSWORD:hMUF98Bsffgeel0y}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=course-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.preferIpAddress=true

# File upload limits
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Actuator Observability
management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.show-details=always

# AI Quiz Consumer Topic
app.kafka.topics.ai-quiz-generated=ai-quiz-generated-topic

