package com.edtech.lms.course.models.entities;

import jakarta.persistence.*;
import lombok.*;
import com.edtech.lms.course.models.enums.DifficultyLevel;
import com.edtech.lms.course.models.enums.QuizType;
import com.fasterxml.jackson.databind.JsonNode;
import org.hibernate.type.SqlTypes;
import java.time.LocalDateTime;

/**
 * QuizQuestion Entity — Represents a quiz question persisted within the course service.
 *
 * <p>Questions come from two sources:
 * <ul>
 *   <li><b>Creator (isAiGenerated = false)</b>: uploaded by a human content creator.</li>
 *   <li><b>AI (isAiGenerated = true)</b>: generated by Gemini via the AI service Kafka pipeline.</li>
 * </ul>
 *
 * <p>The {@code isAiGenerated} flag drives tier-based quiz routing in
 * {@link com.edtech.lms.course.services.EmployeeCourseService}.
 */
@Entity
@Table(name = "svc_course_quiz_questions", indexes = {
    @Index(name = "idx_question_course_id", columnList = "course_id"),
    @Index(name = "idx_question_lesson_id", columnList = "lesson_id")
})
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class QuizQuestion {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long questionId;

    @Column(nullable = false)
    private Long courseId;

    /**
     * Optional: lesson this question belongs to
     */
    @Column(nullable = true)
    private Long lessonId;

    @Column(nullable = false)
    private String concept;

    @Column(nullable = false, columnDefinition = "TEXT")
    private String questionText;

    /**
     * Stored as JSON
     * Example: ["Option A", "Option B", "Option C", "Option D"]
     */
    @Column(columnDefinition = "JSON")
    @org.hibernate.annotations.JdbcTypeCode(SqlTypes.JSON)
    private JsonNode options;

    /**
     * Correct answer (e.g., index or text)
     */
    @Column(nullable = false)
    private String correctAnswer;

    /**
     * PRE_QUIZ — taken before content, drives the 3-factor gating engine.
     * POST_QUIZ — taken after all RECOMMENDED modules complete, triggers uplift computation.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    @Builder.Default
    private QuizType quizType = QuizType.PRE_QUIZ;

    @Enumerated(EnumType.STRING)
    private DifficultyLevel difficultyRating;

    /**
     * {@code true} when this question was generated by the AI pipeline via Kafka
     * (i.e., sourced from Gemini). {@code false} for all human-creator-uploaded questions.
     *
     * <p>Database default is {@code false} so that:
     * <ul>
     *   <li>Newly inserted creator questions require no explicit value.</li>
     *   <li>Existing legacy rows are handled by the data migration script
     *       ({@code UPDATE svc_course_quiz_questions SET is_ai_generated = false
     *        WHERE is_ai_generated IS NULL;}).</li>
     * </ul>
     */
    @Column(nullable = false, columnDefinition = "boolean default false")
    @Builder.Default
    private Boolean isAiGenerated = false;

    /**
     * Used for adaptive learning (1.0 = very difficult, 0.0 = very easy)
     */
    @Column(nullable = true)
    private Double difficultyScore;

    @Column(nullable = false, updatable = false)
    @Builder.Default
    private LocalDateTime createdAt = LocalDateTime.now();

    @Column(nullable = false)
    @Builder.Default
    private LocalDateTime updatedAt = LocalDateTime.now();

    @PreUpdate
    public void preUpdate() {
        this.updatedAt = LocalDateTime.now();
    }
}
