server.port=8084
spring.application.name=lms-identity-service

# Database configuration
spring.datasource.url=${DB_MYSQL_URL:jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/enterprise_db?zeroDateTimeBehavior=convertToNull}
spring.datasource.username=${DB_MYSQL_USERNAME:3tMT9yHQkqHVYMk.root}
spring.datasource.password=${DB_MYSQL_PASSWORD:hMUF98Bsffgeel0y}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Kafka (for publishing USER_DELETED and COMPANY_DELETED)
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.preferIpAddress=true

# JWT Secret
app.jwt.secret=${JWT_SECRET:9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9}
app.jwt.expiration=${JWT_EXPIRATION_MS:86400000}

# Actuator Observability
management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.show-details=always
# Mail
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
