package com.edtech.lms.ai.entity;

import com.edtech.lms.ai.constant.AiConstants;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.CompoundIndex;
import org.springframework.data.mongodb.core.index.CompoundIndexes;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;

/**
 * AiInsightReport — Stores nightly AI-generated insight summaries for course admins.
 *
 * Company Admins see company-scoped reports (insightScope = COMPANY).
 * Super Admins / Creators see cross-company platform reports (insightScope = PLATFORM).
 *
 * Documents are generated by AiInsightScheduler each night and
 * retrieved by AiInsightController on demand.
 */
@Document(collection = AiConstants.COLLECTION_AI_INSIGHTS)
@CompoundIndexes({
    @CompoundIndex(name = "idx_ai_insight_course_company",
                   def = "{'courseId': 1, 'companyId': 1, 'insightScope': 1}")
})
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class AiInsightReport {

    @Id
    private String id;

    @Indexed
    private Long courseId;

    @Indexed
    private Long lessonId;

    /**
     * COMPANY — visible to company admin of this company only.
     * PLATFORM — visible to super admin and creator.
     */
    private String insightScope;

    /**
     * null for PLATFORM-scoped insights (aggregated across all companies).
     */
    private String companyId;

    /**
     * Human-readable AI-generated summary paragraph.
     * Example: "70% of employees in your company paused at minute 4:15 of Lesson 2..."
     */
    private String insightSummary;

    /**
     * AI-identified improvement suggestion for the course creator.
     */
    private String creatorSuggestion;

    /** Number of video sessions analyzed to produce this insight */
    private Integer sessionsAnalyzed;

    @Builder.Default
    private LocalDateTime generatedAt = LocalDateTime.now();
}
