-- =============================================================================
-- Migration: Add is_ai_generated column to svc_course_quiz_questions
--
-- This migration is IDEMPOTENT (safe to run multiple times via IF NOT EXISTS).
--
-- Purpose:
--   Adds the is_ai_generated flag that enables tier-based quiz routing in
--   EmployeeCourseService. Questions are routed based on whether they were
--   generated by the Gemini AI pipeline (true) or uploaded by a human
--   creator (false).
--
-- Legacy data:
--   All existing rows pre-date the AI pipeline and must be classified as
--   human-creator-authored (false). The UPDATE statement below handles this.
--
-- Applied by: Spring JPA / manual execution against enterprise_db schema.
-- Revert:     ALTER TABLE svc_course_quiz_questions DROP COLUMN is_ai_generated;
-- =============================================================================

-- Step 1: Add the column with a nullable type first to handle existing rows
ALTER TABLE svc_course_quiz_questions
    ADD COLUMN IF NOT EXISTS is_ai_generated BOOLEAN NOT NULL DEFAULT false;

-- Step 2: Backfill any rows that might have NULL (handles partial migration runs)
UPDATE svc_course_quiz_questions
SET is_ai_generated = false
WHERE is_ai_generated IS NULL;

-- Step 3: Add an index to optimise the primary routing query used in EmployeeCourseService:
--   SELECT * FROM svc_course_quiz_questions
--   WHERE course_id = ? AND quiz_type = ? AND is_ai_generated = ?
-- Without this index, every quiz retrieval is a full table scan.
CREATE INDEX IF NOT EXISTS idx_quiz_course_type_ai
    ON svc_course_quiz_questions (course_id, quiz_type, is_ai_generated);
