package com.edtech.lms.ai.client;

import com.edtech.lms.ai.constant.AiConstants;
import com.edtech.lms.ai.exception.AiProviderUnavailableException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Component;
import org.springframework.web.client.RestTemplate;

/**
 * GeminiClient — HTTP client for Google Gemini Generative Language API.
 *
 * Uses the Gemini 1.5 Flash model via REST (no SDK required for this version).
 * API key is injected via environment variable — never hardcoded.
 *
 * Retry logic: Attempts MAX_AI_RETRY_COUNT times with a 1-second back-off.
 * If all retries fail, throws AiProviderUnavailableException for global handler.
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class GeminiClient {

    private final RestTemplate restTemplate;
    private final ObjectMapper objectMapper;

    @Value("${gemini.api.key}")
    private String apiKey;

    @Value("${gemini.api.base-url}")
    private String baseUrl;

    @Value("${gemini.api.model}")
    private String model;

    /**
     * Sends a prompt to the Gemini API and returns the raw text response.
     *
     * @param systemInstruction system-level instruction (role of the AI)
     * @param userPrompt        user-level prompt (the actual question/task)
     * @return raw text generated by Gemini
     * @throws AiProviderUnavailableException if all retries are exhausted
     */
    public String generateText(final String systemInstruction, final String userPrompt) {
        final String url = buildUrl();
        final String requestBody = buildRequestBody(systemInstruction, userPrompt);

        for (int attempt = 1; attempt <= AiConstants.MAX_AI_RETRY_COUNT; attempt++) {
            try {
                final String response = callGeminiApi(url, requestBody);
                return extractTextFromResponse(response);
            } catch (Exception ex) {
                log.warn("Gemini API attempt {}/{} failed: {}", attempt, AiConstants.MAX_AI_RETRY_COUNT, ex.getMessage());
                if (attempt < AiConstants.MAX_AI_RETRY_COUNT) {
                    sleepOneSecond();
                }
            }
        }

        throw new AiProviderUnavailableException(
                "Gemini API is unavailable after " + AiConstants.MAX_AI_RETRY_COUNT + " attempts.");
    }

    private String callGeminiApi(final String url, final String requestBody) {
        final HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        final HttpEntity<String> httpEntity = new HttpEntity<>(requestBody, headers);
        return restTemplate.postForObject(url, httpEntity, String.class);
    }

    private String buildUrl() {
        // Pattern: baseUrl/models/model:generateContent?key=apiKey
        return baseUrl + "/models/" + model + ":generateContent?key=" + apiKey;
    }

    private String buildRequestBody(final String systemInstruction, final String userPrompt) {
        // Gemini REST API (v1beta) uses snake_case: system_instruction
        return String.format(
            "{\"system_instruction\":{\"parts\":[{\"text\":\"%s\"}]},"
            + "\"contents\":[{\"parts\":[{\"text\":\"%s\"}]}]}",
            escapeJson(systemInstruction),
            escapeJson(userPrompt)
        );
    }

    /**
     * Extracts the text content from Gemini's nested response JSON.
     * Path: candidates[0].content.parts[0].text
     */
    private String extractTextFromResponse(final String responseJson) {
        try {
            final JsonNode root = objectMapper.readTree(responseJson);
            return root.path("candidates")
                       .path(0)
                       .path("content")
                       .path("parts")
                       .path(0)
                       .path("text")
                       .asText("");
        } catch (Exception ex) {
            throw new AiProviderUnavailableException("Failed to parse Gemini response: " + ex.getMessage());
        }
    }

    private String escapeJson(final String text) {
        // Basic escaping to prevent JSON injection in prompt strings
        return text.replace("\\", "\\\\")
                   .replace("\"", "\\\"")
                   .replace("\n", "\\n")
                   .replace("\r", "\\r");
    }

    private void sleepOneSecond() {
        try {
            Thread.sleep(1000);
        } catch (InterruptedException ie) {
            Thread.currentThread().interrupt();
            log.warn("Retry sleep interrupted.");
        }
    }
}
